name: autobuild-supplements

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'my-filter/**'

permissions:
  contents: write

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python-abp
      run: |
        python -m pip install --upgrade pip
        pip install python-abp
    - name: Build
      run: |
        flrender $GITHUB_WORKSPACE/filter-templates/b.template $GITHUB_WORKSPACE/internal-usage/b.txt
        flrender $GITHUB_WORKSPACE/filter-templates/supplements.template $GITHUB_WORKSPACE/unified-filter/supplements.txt
    - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Supplements filter Auto-Build"
        git push
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
